=== jruillier/scb-wine-selector-assistant/src/jsMain/resources/wsa.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://aronnax.eu/wsa.schema.json",
  "title": "Wine Selector Assistant items",
  "description": "Items tree",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "label": {
        "type": "string"
      },
      "imageSrc": {
        "type": ["string","null"]
      },
      "targetHref": {
        "type": ["string","null"]
      },
      "children": {
          "$ref": "#"
      }
    },
    "required": ["label"]
  }
}

=== jruillier/scb-wine-selector-assistant/src/jsMain/resources/wine-selector-items.wsa.json
[
  {
    "label": "Selon mes goûts",
    "imageSrc": null,
    "targetHref": null,
    "children": [
      {
        "label": "Fruité",
        "imageSrc": null,
        "targetHref": "https://simplecommebacchus.fr/collections/alsace",
        "children": []
      },
      {
        "label": "Souple et léger",
        "imageSrc": null,
        "targetHref": "https://simplecommebacchus.fr/collections/bourgogne",
        "children": []
      },
      {
        "label": "Liquoreux / Sucré",
        "imageSrc": null,
        "targetHref": "https://simplecommebacchus.fr/collections/beaujolais",
        "children": []
      },
      {
        "label": "Sec et Minéral",
        "imageSrc": null,
        "targetHref": "https://simplecommebacchus.fr/collections/cote-du-rhone",
        "children": []
      },
      {
        "label": "Puissant",
        "imageSrc": null,
        "targetHref": "https://simplecommebacchus.fr/collections/sud-ouest",
        "children": []
      },
      {
        "label": "Boisé",
        "imageSrc": null,
        "targetHref": "https://simplecommebacchus.fr/collections/bordeaux",
        "children": []
      }
    ]
  },
  {
    "label": "Selon mon repas",
    "imageSrc": null,
    "targetHref": null,
    "children": [
      {
        "label": "Apéritif",
        "imageSrc": null,
        "targetHref": null,
        "children": [
          {
            "label": "Boudin",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Crevettes",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          }
        ]
      },
      {
        "label": "Entrée",
        "imageSrc": null,
        "targetHref": null,
        "children": [
          {
            "label": "Concombre",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Avocat",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Crabe farci",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          }
        ]
      },
      {
        "label": "Plat Principal",
        "imageSrc": null,
        "targetHref": null,
        "children": [
          {
            "label": "Colombo",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Cour-bouillon de poisson",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Viande grillée",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          }
        ]
      },
      {
        "label": "Fromage",
        "imageSrc": null,
        "targetHref": null,
        "children": [
          {
            "label": "Camembert",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Morbier",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Chèvre",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          }
        ]
      },
      {
        "label": "Dessert",
        "imageSrc": null,
        "targetHref": null,
        "children": [
          {
            "label": "Crème brulée",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Ananas",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          },
          {
            "label": "Chocolat",
            "imageSrc": null,
            "targetHref": null,
            "children": []
          }
        ]
      }
    ]
  }
]
